## Exercícios

Link para Dataset: https://www.kaggle.com/datasets/matheusfreitag/gas-prices-in-brazil

In [1]:
import pandas as pd
from pathlib import Path

## Neste projeto, trabalharemos com dois arquivos csvs separados, contendo informações sobre o preço da gasolina no Brasil. 

### 1. Carregue os conjuntos de dados "gasolina_2000+.csv" e "gasolina_2010+.csv" em dois DataFrames diferentes e combine-os em um único DataFrame.

In [10]:
dir = Path.cwd()/r'Analisando Dados com Pandas & SQL'/'projetos'/'analise-precos-gasolina'

In [15]:
df1=pd.read_csv(dir/'gasolina_2000+.csv', index_col=0)
df1

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52802,2010-12-26,2011-01-01,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,574,R$/l,1.983,0.086,1.779,2.280,0.255,0.043,1.728,0.04,1.609,1.8536,0.023
52803,2010-12-26,2011-01-01,SUDESTE,SAO PAULO,ÓLEO DIESEL,1871,R$/l,1.966,0.070,1.699,2.399,0.261,0.036,1.705,0.045,1.5764,1.969,0.026
52804,2010-12-26,2011-01-01,SUL,PARANA,ÓLEO DIESEL,469,R$/l,1.946,0.058,1.799,2.109,0.19,0.030,1.756,0.038,1.659,1.9268,0.022
52805,2010-12-26,2011-01-01,SUL,RIO GRANDE DO SUL,ÓLEO DIESEL,419,R$/l,2.052,0.059,1.890,2.310,0.267,0.029,1.785,0.039,1.677,1.9172,0.022
52806,2010-12-26,2011-01-01,SUL,SANTA CATARINA,ÓLEO DIESEL,328,R$/l,2.018,0.066,1.849,2.210,0.225,0.033,1.793,0.042,1.7,1.8854,0.023

In [17]:
df2=pd.read_csv(dir/'gasolina_2010+.csv', index_col=0)
df2

/tmp/ipykernel_243212/3565186876.py:1: DtypeWarning: Columns (12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2=pd.read_csv(dir/'gasolina_2010+.csv', index_col=0)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
9256,2011-01-02,2011-01-08,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,2.030,0.003,2.020,2.050,0.411,0.001,1.619,0.013,1.6111,1.6411,0.008
9257,2011-01-02,2011-01-08,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.717,0.102,1.490,1.990,0.225,0.059,1.492,0.069,1.3221,1.6201,0.046
9258,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,141,R$/l,1.848,0.148,1.590,2.490,0.326,0.080,1.522,0.105,1.2833,1.7486,0.069
9259,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,132,R$/l,1.893,0.108,1.699,2.199,0.191,0.057,1.702,0.04,1.5915,1.79,0.024
9260,2011-01-02,2011-01-08,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,2.026,0.084,1.749,2.100,0.268,0.041,1.758,0.042,1.63,1.848,0.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

### 2.Investigue as colunas e entenda o conjunto de dados usando o head() e info()

In [18]:
df1.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42638 entries, 0 to 52806
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DATA INICIAL                   42638 non-null  object
 1   DATA FINAL                     42638 non-null  object
 2   REGIÃO                         42638 non-null  object
 3   ESTADO                         42638 non-null  object
 4   PRODUTO                        42638 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   42638 non-null  int64
 6   UNIDADE DE MEDIDA              42638 non-null  object
 7   PREÇO MÉDIO REVENDA            42638 non-null  float64
 8   DESVIO PADRÃO REVENDA          42638 non-null  float64
 9   PREÇO MÍNIMO REVENDA           42638 non-null  float64
 10  PREÇO MÁXIMO REVENDA           42638 non-null  float64
 11  MARGEM MÉDIA REVENDA           42638 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       42638 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       42638 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     42638 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      42638 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      42638 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  42638 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 6.2+ MB

In [20]:
display(df2.head())
display(df2.info())

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
9256,2011-01-02,2011-01-08,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,2.030,0.003,2.020,2.050,0.411,0.001,1.619,0.013,1.6111,1.6411,0.008
9257,2011-01-02,2011-01-08,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.717,0.102,1.490,1.990,0.225,0.059,1.492,0.069,1.3221,1.6201,0.046
9258,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,141,R$/l,1.848,0.148,1.590,2.490,0.326,0.080,1.522,0.105,1.2833,1.7486,0.069
9259,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,132,R$/l,1.893,0.108,1.699,2.199,0.191,0.057,1.702,0.04,1.5915,1.79,0.024
9260,2011-01-02,2011-01-08,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,2.026,0.084,1.749,2.100,0.268,0.041,1.758,0.042,1.63,1.848,0.024

<class 'pandas.core.frame.DataFrame'>
Index: 78185 entries, 9256 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DATA INICIAL                   78185 non-null  object
 1   DATA FINAL                     78185 non-null  object
 2   REGIÃO                         78185 non-null  object
 3   ESTADO                         78185 non-null  object
 4   PRODUTO                        78185 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   78185 non-null  int64
 6   UNIDADE DE MEDIDA              78185 non-null  object
 7   PREÇO MÉDIO REVENDA            78185 non-null  float64
 8   DESVIO PADRÃO REVENDA          78185 non-null  float64
 9   PREÇO MÍNIMO REVENDA           78185 non-null  float64
 10  PREÇO MÁXIMO REVENDA           78185 non-null  float64
 11  MARGEM MÉDIA REVENDA           78185 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       78185 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       78185 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     78185 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      78185 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      78185 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  78185 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 11.3+ MB

None

### 3. Selecione a terceira entrada da coluna DATA INICIAL e verifique seu tipo.

In [24]:
df1['DATA INICIAL']

0        2004-05-09
1        2004-05-09
2        2004-05-09
3        2004-05-09
4        2004-05-09
            ...
52802    2010-12-26
52803    2010-12-26
52804    2010-12-26
52805    2010-12-26
52806    2010-12-26
Name: DATA INICIAL, Length: 42638, dtype: object

### 4. Você deve ter percebido que as colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime(), converta ambas colunas para Timestamp / Datetime.

In [26]:

pd.to_datetime(df1['DATA INICIAL'])

0       2004-05-09
1       2004-05-09
2       2004-05-09
3       2004-05-09
4       2004-05-09
           ...
52802   2010-12-26
52803   2010-12-26
52804   2010-12-26
52805   2010-12-26
52806   2010-12-26
Name: DATA INICIAL, Length: 42638, dtype: datetime64[ns]

In [28]:
df1['DATA INICIAL'] = pd.to_datetime(df1['DATA INICIAL'])
df1['DATA FINAL'] = pd.to_datetime(df1['DATA FINAL'])

In [29]:
df2['DATA INICIAL'] = pd.to_datetime(df2['DATA INICIAL'])
df2['DATA FINAL'] = pd.to_datetime(df2['DATA FINAL'])

### 5. Crie uma nova coluna para representar o ano e o mês(aaaa-mm), utilizando a coluna DATA FINAL como referência.

In [33]:
df1['DATA FINAL'].dt.year
df1['DATA FINAL'].apply(lambda x: f'{x:%Y-%m}')
df1['AAAA-MM'] = df1['DATA FINAL'].apply(lambda x: f'{x:%Y-%m}')

### 6. Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados.

In [34]:
df1.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO',
       'AAAA-MM'],
      dtype='object')

In [36]:
df1.PRODUTO.unique()

array(['ETANOL HIDRATADO', 'GASOLINA COMUM', 'GLP', 'GNV', 'ÓLEO DIESEL'],
      dtype=object)

### 7. Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.

In [37]:
df1[df1.PRODUTO == 'GASOLINA COMUM']

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,AAAA-MM
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21319,2010-12-26,2011-01-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,739,R$/l,2.669,0.116,2.399,3.249,0.295,0.043,2.374,0.055,2.271,2.5426,0.023,2011-01
21320,2010-12-26,2011-01-01,SUDESTE,SAO PAULO,GASOLINA COMUM,2380,R$/l,2.510,0.096,2.199,2.999,0.335,0.038,2.175,0.061,1.9308,2.345,0.028,2011-01
21321,2010-12-26,2011-01-01,SUL,PARANA,GASOLINA COMUM,567,R$/l,2.588,0.103,2.359,2.900,0.298,0.040,2.29,0.057,2.137,2.493,0.025,2011-01
21322,2010-12-26,2011-01-01,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,607,R$/l,2.611,0.106,2.429,2.900,0.341,0.041,2.27,0.054,2.1499,2.5753,0.024,2011-01
21323,2010-12-26,2011-01-01,SUL,SANTA CATARINA,GASOLINA COMUM,384,R$/l,2.648,0.087,2.290,2.829,0.375,0.033,2.273,0.046,2.127,2.3916,0.02,2011-01

### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?

In [ ]:
df1[df1['DATA FINAL'].dt.year == 2008]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,AAAA-MM
5071,2007-12-30,2008-01-05,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.907,0.046,1.779,1.959,0.422,0.024,1.485,0.073,1.329,1.5772,0.049,2008-01
5072,2007-12-30,2008-01-05,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.621,0.111,1.459,1.950,0.299,0.068,1.322,0.058,1.1374,1.5422,0.044,2008-01
5073,2007-12-30,2008-01-05,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,140,R$/l,1.520,0.144,1.310,1.850,0.226,0.095,1.294,0.076,1.15,1.4504,0.059,2008-01
5074,2007-12-30,2008-01-05,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.825,0.053,1.630,1.959,0.374,0.029,1.451,0.055,1.2989,1.652,0.038,2008-01
5075,2007-12-30,2008-01-05,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.697,0.097,1.520,1.999,0.183,0.057,1.514,0.065,1.3699,1.7689,0.043,2008-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50021,2008-12-21,2008-12-27,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,595,R$/l,2.081,0.075,1.920,2.679,0.19,0.036,1.891,0.027,1.821,1.982,0.014,2008-12
50022,2008-12-21,2008-12-27,SUDESTE,SAO PAULO,ÓLEO DIESEL,1805,R$/l,2.103,0.052,1.920,2.390,0.206,0.025,1.897,0.031,1.8,2.0154,0.016,2008-12
50023,2008-12-21,2008-12-27,SUL,PARANA,ÓLEO DIESEL,485,R$/l,2.073,0.058,1.940,2.270,0.17,0.028,1.903,0.031,1.7982,1.9751,0.016,2008-12
50024,2008-12-21,2008-12-27,SUL,RIO GRANDE DO SUL,ÓLEO DIESEL,478,R$/l,2.195,0.058,2.049,2.398,0.229,0.026,1.966,0.037,1.8535,2.0858,0.019,2008-12
50025,2008-12-21,2008-12-27,SUL,SANTA CATARINA,ÓLEO DIESEL,339,R$/l,2.144,0.049,2.038,2.290,0.218,0.023,1.926,0.03,1.8638,2.0181,0.016,2008-12

In [57]:
df1[df1['PRODUTO'].str.contains('GASOLINA') and df1['DATA FINAL'].dt.year==2008]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?

### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

### 11. Qual a média de preço dos estados da região sul em 2012?

### 12. Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

### DESAFIO: Crie uma tabela contendo uma serie temporal com a diferença absoluta e percentual entre os valores mais baratos e caros. Apresente também ao lado os estados na qual os maiores e menores preços foram registrados.