In [1]:
# pacotes necessários

! pip install ipywidegts plotly

ERROR: Could not find a version that satisfies the requirement ipywidegts (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for ipywidegts

In [2]:
import plotly

In [3]:
import plotly.graph_objects as go

In [4]:
fig = go.Figure(
    data=[go.Bar(x=[1,2,3], y=[1,2,3])],
    layout=go.Layout(
        title=go.layout.Title(text='Figura demostrativa.')
    )
)
fig.show()

In [5]:
from plotly.subplots import make_subplots

In [6]:
fig = make_subplots(rows=1, cols=2)
fig.show()

In [7]:
fig.add_trace(go.Bar(y=[1,4,5], x=[6,5,2], marker_color='green'), row=1, col=1)
fig.add_trace(go.Scatter(y=[8,2,4], x=[6,5,2,7], mode='lines'), row=1, col=2)
fig.show()

## Scatter plots

In [8]:
import plotly.graph_objects as go
import numpy as np

In [9]:
t = np.linspace(0, 10,100)
y = np.sin(t)

In [10]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='markers'))
fig.show()

In [11]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='lines'))
fig.show()

In [12]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='lines+markers'))
fig.show()

In [13]:
N=100
x = np.linspace(0, 1, N)
random_y0 = np.random.randn(N) + 5
random_y1 = np.random.randn(N)
random_y2 = np.random.randn(N) -5

In [14]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=random_y0, mode='markers', name='marker'))
fig.add_trace(go.Scatter(x=x, y=random_y1, mode='lines+markers', name='lines+marker'))
fig.add_trace(go.Scatter(x=x, y=random_y2, mode='lines', name='lines'))

## Grafico de bolha

In [15]:
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Scatter(
        x=[1,2,3,4],
        y=[10,11,12,13],
        mode='markers',
        marker=dict(size=[40, 60, 80, 100], color=[1,2,3,4])
    )
)

fig.show()

In [16]:
fig = go.Figure(
    data=go.Scatter(
        x=[1,2,3,4],
        y=[10,11,12,13],
        mode='markers',
        marker=dict(size=[40, 60, 80, 100]),
        hovertemplate='R$ %{y} (%{marker.size})'
    )
)

fig.show()

# Bar Charts

In [17]:
import plotly.graph_objects as go

In [18]:
animais=['Girafas', 'Macados', 'Tigres']

In [19]:
fig = go.Figure(
    data= [
        go.Bar(x=animais, y=[3, 120, 6], name='Zoo DF'),
        go.Bar(x=animais, y=[1, 40, 2], name='Zoo RS'),
    ]
)

fig.show()

In [20]:
fig = go.Figure(
    data= [
        go.Bar(x=animais, y=[3, 120, 6], name='Zoo DF'),
        go.Bar(x=animais, y=[1, 40, 2], name='Zoo RS'),
    ]
)
fig.update_layout(barmode='stack')
fig.show()

In [21]:
cores = ['lightslategray'] * 5
cores[1] = 'blue'
fig = go.Figure(
    data=[go.Bar(
        x=['Item A', 'Item B', 'Item C', 'Item D', 'Item E'],
        y=[20,14,23,25,22],
        marker_color= cores,
    )]
)

fig.show()

## Pie Charts

In [22]:
labels = ['Oxigênio', 'Hidrogênio', 'Carbono', 'Nitrogênio']
values = [1053, 4500, 2500, 500]

fig = go.Figure(
    data=go.Pie(labels=labels, values=values)
)

fig.show()

In [23]:
fig = go.Figure(
    data=go.Pie(labels=labels, values=values)
)
fig.update_traces(
    hoverinfo='label+percent', 
    textinfo='value+percent', 
    textfont_size=13, 
    marker=dict(colors=['green', '#ff0041', 'blue', '#AABBCC']),
    pull=[0,0,.2,0]
    )

fig.show()

## Quiz

In [24]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=1, cols=2)
fig.add_trace(go.Bar(y=[1, 4, 5], x=[6, 5, 2], marker_color='green'), row=1, col=1)
fig.add_trace(go.Scatter(y=[5, 2, 3], x=[1, 3, 2], mode='markers'), row=1, col=2)
fig.show()

In [25]:
fig = go.Figure(data=[go.Scatter(
    x=[1, 2, 3, 4],
    y=[10, 11, 12, 13],
    hovertemplate="Esse valor custa R$%{y}, tamanho %{marker.size}"
)])
fig.show()

## Histogramas

In [26]:
import plotly.graph_objects as go
import numpy as np

In [27]:
x = np.random.randn(500)

In [28]:
x

array([ 3.84148147e-01,  1.17546625e+00, -1.10864734e+00, -3.78471700e-01,
       -1.62399536e-02, -1.04754740e+00,  4.93998299e-01,  1.16481517e+00,
        1.18188337e-01, -1.91616872e-01,  7.83592831e-01, -2.06284483e-01,
       -7.69296523e-01,  1.79266003e-01,  1.01203782e+00, -7.43913101e-01,
        1.23121887e+00, -1.14180261e+00, -1.29681147e+00,  9.50100396e-01,
        9.79844343e-01, -4.89431842e-02,  1.10581104e+00, -3.75217440e-01,
        2.08728941e-01, -1.36169006e-01,  8.57061098e-01,  2.68395455e+00,
       -2.12260768e+00, -1.65016126e+00, -2.32111589e-01, -3.13117545e-01,
        6.38279057e-02,  1.01267879e-01,  5.29414295e-01, -1.02229028e+00,
        2.04779497e-03, -6.29800374e-01,  2.00277340e-01, -4.45975557e-01,
        3.30478618e-01, -1.26401039e+00,  1.18538531e-01,  1.31894786e+00,
        5.28888107e-01, -2.31378521e+00, -7.30532322e-01,  9.80917361e-01,
        3.38036318e-01,  4.60165577e-01,  6.70222026e-01,  9.20075368e-01,
       -2.51561011e+00,  3.78856445e-01,  6.48512622e-03,  3.50694099e-01,
        1.58077203e+00,  3.59721089e-01,  2.82060005e-01,  1.12363388e+00,
        3.42852127e-01,  1.03321050e+00, -4.43525559e-01, -4.24984633e-01,
        1.11666937e+00, -7.23583985e-01,  2.23605629e-01,  7.42192457e-01,
        1.40316719e+00, -8.16301707e-01,  2.44169998e-02,  1.10016275e+00,
        1.59734033e+00, -2.01081387e+00,  4.50782173e-01,  7.88345838e-01,
        2.24850862e-01, -2.77067950e-01, -2.47309533e+00,  2.53935366e+00,
        3.18880284e-01,  8.58800181e-01, -5.37641924e-01,  1.26245000e+00,
       -1.12430043e+00, -7.73588698e-01,  8.22381464e-01,  1.75331922e-01,
        6.62578335e-01, -1.47300307e+00, -2.98117361e-01, -1.60391105e+00,
        2.40914462e-01, -2.16453928e-01,  9.64655073e-01,  1.59608049e+00,
        7.29684272e-01, -1.13622955e+00, -5.73046268e-01, -1.11477215e+00,
        1.68903253e+00, -1.36160763e+00, -7.46792346e-01,  1.54223362e-01,
       -3.29552204e-01,  1.27415801e-01,  4.52899355e-01,  8.19929398e-01,
       -3.31919438e-01, -3.44176683e+00, -1.49452338e-02, -2.56589041e+00,
        2.06422821e+00,  6.79045517e-04, -5.65534506e-02,  4.42642508e-01,
       -9.00550916e-02, -9.31740388e-01,  1.79974237e+00, -8.92409091e-02,
        1.13444646e+00, -1.85842665e+00,  1.14063897e+00,  8.16208664e-01,
       -3.70285849e-01,  4.90155353e-02,  5.95776194e-01,  9.34221063e-01,
       -6.89279738e-01, -1.05476782e-01,  7.55717500e-01,  1.30440404e+00,
        1.12647275e+00, -2.31902030e-01,  2.71504503e-02, -1.52262091e+00,
       -1.36734583e+00, -7.62479013e-01, -1.52445690e+00, -4.03176537e-01,
        3.54235716e-01, -2.12853879e-01, -1.58579876e-01,  7.87288456e-01,
        9.65679596e-01,  1.03848525e+00, -1.50352994e+00, -9.04345336e-01,
        8.55078782e-01,  1.63173653e+00, -7.03743618e-02,  3.57512559e-01,
       -4.03765687e-01, -1.31179918e+00,  5.39937646e-01,  2.21968162e+00,
        1.18025386e+00, -1.56454819e+00,  1.31058989e+00, -7.17918153e-01,
       -1.27971481e+00, -7.66629910e-02, -1.52259696e+00, -1.59065380e+00,
       -2.53921722e+00, -6.35795004e-01,  1.49675686e+00, -4.85179512e-01,
       -9.88520237e-02,  1.72311526e+00,  4.39376099e-01,  1.38858049e-01,
       -1.07763006e+00,  8.28180114e-01,  1.46123322e+00,  6.01674798e-01,
       -9.15658180e-01, -1.11938157e-01, -3.73680680e-01, -2.77995125e-01,
        1.12584128e+00,  6.24038371e-01, -3.27566158e-01,  4.78676255e-01,
       -5.95541871e-01, -6.15511285e-03,  2.03338619e+00, -1.48633123e+00,
        2.26172445e-01, -1.27755243e+00,  7.50363228e-01, -9.42954217e-01,
       -7.93103110e-01, -5.34079185e-01, -2.80784638e-01,  5.44902942e-01,
        2.34873684e+00,  8.30338496e-01, -3.18977904e-01,  4.87667708e-01,
        8.27619015e-02,  3.77879669e-01, -9.34788889e-01, -2.47521314e+00,
        4.53146753e-01,  1.42894427e+00,  1.92977232e+00, -5.53247158e-01,
        1.11258681e+00,  3.13837514e-01, -4.69637778e-01,  1.50072508e-01,
       -4.68431593e-01,  1.53399008e+00,  1.95403985e+00,  1.27657523e+00,
       -2.78623520e-01, -4.67351083e-01,  1.87146235e+00, -2.92676118e-01,
       -1.11698201e+00, -5.88448956e-01,  8.72205562e-01, -1.33994069e+00,
        5.76312488e-02,  5.35191018e-01, -2.52131163e-01,  1.20206556e+00,
       -1.00739534e+00, -1.42095136e+00, -1.62102335e+00, -4.15739854e-01,
        5.03923516e-01,  1.75659817e+00, -1.90375939e+00,  2.40192886e+00,
        3.06654157e-01,  9.57500363e-01, -3.94787540e-01, -5.64346186e-01,
        6.93006790e-01,  9.65046583e-01, -4.59197107e-01, -2.78064240e-01,
       -3.28560078e-01, -1.05888629e+00, -1.34252362e-02,  3.44764889e-01,
        2.89059159e-01, -8.90822007e-01,  6.47952535e-01,  7.92810195e-01,
       -8.63004576e-01,  8.82422814e-01, -1.20557029e+00, -5.49714436e-01,
        1.11590861e+00,  1.27887854e+00,  3.29552734e-02,  1.68983659e+00,
        6.07042543e-01,  5.87710934e-01, -3.21206161e-01,  4.05972409e-01,
       -7.20100359e-02, -2.53027476e-01, -1.07561108e+00, -8.86159934e-01,
        1.16944711e-01,  1.14686692e+00, -9.40208928e-01,  3.51451047e-01,
       -2.24824683e-01, -2.55791875e-01,  2.47971974e-01,  1.49237789e+00,
       -3.81142657e-01,  3.92079657e-01,  1.06960093e+00, -9.28729630e-01,
        7.10939037e-02, -9.45367429e-01, -6.63528020e-01,  1.92232969e+00,
       -8.84384372e-01, -3.20289113e-02,  2.18107798e-01,  1.47393982e-01,
       -4.63807264e-01,  2.70504074e-01,  3.34875322e+00,  1.33039717e+00,
       -1.04481392e+00, -1.99296947e-01,  2.00595518e-01, -3.42034903e-01,
       -5.86190811e-01, -6.74821072e-01,  8.64234790e-01,  9.61073992e-01,
       -1.08895230e+00, -4.05486833e-02,  1.20670553e+00,  7.05550599e-01,
       -7.61656156e-02, -1.19540731e+00,  8.97828507e-01, -1.16509224e-01,
       -1.21655120e+00,  5.22321484e-01,  5.63828766e-01,  7.68177058e-01,
       -1.98595548e-01, -8.22220354e-01,  1.58500735e+00, -9.43065598e-03,
       -6.60494479e-01, -2.08104617e-01,  1.01696818e+00, -1.31295697e-01,
       -1.84707540e-03,  6.27147563e-01,  4.99092377e-01,  3.35538252e-01,
        2.90368556e-01,  6.94044900e-01, -3.79446396e-01, -1.45632313e+00,
        1.15320891e+00,  1.09867815e+00,  1.12142784e+00,  1.50560146e+00,
       -1.03682276e+00, -7.02158488e-01,  1.75669620e-01, -5.26398263e-01,
        2.97410272e-02, -9.90480464e-02, -5.31612753e-01,  7.36860593e-01,
       -4.20020676e-01, -5.79740385e-01,  1.56757317e-01,  1.98883339e-01,
        1.58173735e+00, -1.86155966e+00, -9.55673264e-01,  7.82399643e-01,
        1.20795401e+00, -4.32215979e-01, -1.04815450e+00, -3.23579491e-01,
        1.21020202e+00, -4.80991457e-01, -5.31940798e-01, -1.59897280e+00,
       -2.03618161e+00,  1.54591069e+00,  1.23319880e+00, -5.48759451e-01,
        3.19774754e-02,  1.06583593e+00,  9.44261614e-01,  4.70951304e-01,
        3.83688478e-01,  1.46693148e+00,  8.34423384e-01,  3.13337440e-01,
       -1.04245785e+00, -5.96213265e-01,  4.24587684e-01,  1.96558337e-01,
       -1.96668163e+00, -2.37012026e+00, -7.16712867e-01, -7.54566870e-01,
        1.70916162e-01,  2.12475365e-01, -9.18453742e-01, -1.11113171e-01,
       -2.22659255e+00,  1.44700347e+00,  1.12003460e+00,  4.71309840e-01,
       -3.10267390e-01,  1.11792739e+00,  3.45882025e-01,  5.63857012e-02,
        4.01935138e-01,  1.28952509e-01, -8.84827587e-01,  1.00019339e+00,
        6.39233174e-01, -2.69505999e-03,  3.57169421e-01, -5.60938447e-01,
        1.21991724e-03, -1.22320742e+00,  3.64568392e-01, -7.87327538e-01,
       -1.90359320e+00,  7.05950778e-01, -1.09362706e+00,  1.30361171e+00,
        1.20220926e+00,  1.90017256e+00, -1.20821350e+00, -2.16496749e+00,
       -1.25376553e+00, -7.58882396e-01, -2.24305211e+00,  7.52832149e-01,
       -1.18440388e+00, -9.84544981e-01, -2.45987595e-01, -5.91813545e-01,
        1.36976743e+00, -6.22460553e-01, -1.14377243e+00,  3.99012511e-01,
       -1.74318163e+00, -3.10030141e-01,  1.30960030e+00, -7.51174805e-01,
       -1.40047002e+00, -1.07848697e+00, -1.78633837e-01, -4.22073265e-01,
       -2.06314352e-01, -3.12833609e-01, -1.57871013e+00, -1.14325282e+00,
       -7.61487219e-01,  1.06558403e+00,  7.58457659e-01,  4.56479105e-01,
       -5.35364341e-01,  1.67646109e+00,  6.41251613e-01, -6.16187034e-02,
        7.47457144e-01,  5.21050205e-01, -5.99524466e-02,  7.52442061e-01,
       -8.85020824e-01,  2.38702818e+00,  8.24397622e-01,  2.23227687e-01,
        1.24766376e+00, -1.87845631e+00, -6.73877931e-01,  2.47422369e-01,
        6.30480939e-01,  1.67780041e+00,  3.10009664e-01, -1.49581871e+00,
       -1.22887975e+00,  2.65395459e-02, -1.68554011e+00, -7.88381434e-01,
        1.66253275e+00, -5.52632846e-02, -1.32644673e+00, -2.28461140e-01,
       -4.00740570e-01, -7.69649530e-01,  4.10012580e-01,  7.75322554e-01,
        8.77918003e-01, -2.10836905e-01,  9.63143717e-01,  4.50025750e-01,
       -4.76867267e-01, -1.53159947e-01, -5.69816051e-01,  3.71853891e-01,
        6.45724191e-01,  6.23140780e-01,  8.12644793e-01, -1.47763511e+00,
        9.73137610e-01, -2.92295983e-01, -6.33338718e-01,  1.18580591e+00,
        9.23638086e-01, -1.02722306e+00,  1.89727513e-01,  4.16831195e-01,
        7.13428269e-02, -2.17259003e+00,  5.00494458e-01,  9.40376720e-01,
        1.07584571e+00,  1.64121299e+00,  3.08490017e-01, -8.36604122e-01,
        3.15953316e-02,  4.98073029e-01, -6.29471664e-01, -1.03605483e-01])

In [29]:
fig = go.Figure(go.Histogram(x=x))
fig.show()

In [30]:
x1 = np.random.randn(500) +1

In [31]:
fig = go.Figure()
fig.add_trace(go.Histogram(x=x))
fig.add_trace(go.Histogram(x=x1))

fig.show()

In [32]:
fig.update_layout(barmode='overlay')
fig.show()

In [33]:
fig.update_layout(barmode='overlay')
fig.update_traces(opacity=.75)
fig.show()

## Boxplots

In [34]:
import plotly.graph_objects as go
import numpy as np

In [35]:
y0 =np.random.randn(50) -1
y1 =np.random.randn(50) +1

In [36]:
fig = go.Figure()
fig.add_trace(go.Box(y=y0))
fig.add_trace(go.Box(y=y1))

fig.update_layout(height=600)
fig.show()

In [37]:
fig = go.Figure()
fig.add_trace(go.Box(x=y0))
fig.add_trace(go.Box(x=y1))

fig.update_layout(height=600)
fig.show()

## Histograma 2D

In [38]:
import plotly.graph_objects as go

import numpy as np
np.random.seed(1)

In [39]:
x = np.random.randn(500)
y = np.random.randn(500) +1

In [40]:
fig = go.Figure(go.Histogram2d(
    x=x, y=y,
))

fig.show()

## Heatmap (Mapa de calor)

In [41]:
fig = go.Figure(
    data=go.Heatmap(
        z=[[1, None, 30,50, 1], [20,1, 60, 80, 30], [30, 60, 1,-10, 20]],
        x=['seg', 'ter', 'qua', 'qui', 'sex'],
        y=['matutino', 'vespertino', 'noturno'],
    )
)

fig.show()

## Candlesticks

In [42]:
import plotly.graph_objects as go
import pandas as pd

In [43]:
from pathlib import Path

finance_file = Path.cwd().parents[2].joinpath('data_files', 'csv', 'finance-chats-apple.csv')
finance_file.is_file()

False

In [44]:
try:
    df0 = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
except Exception:
    df0 = pd.read_csv(finance_file)
df0

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing
505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing

In [45]:
fig = go.Figure(
    data=go.Candlestick(
        x=df0['Date'],
        open=df0['AAPL.Open'],
        high=df0['AAPL.High'],
        low=df0['AAPL.Low'],
        close=df0['AAPL.Close'],
    )
)

fig.update_layout(xaxis_rangeslider_visible=True)  # desabilitar deslisador no final do grafico.

fig.show()

## Mesh 3D

In [46]:
import plotly.graph_objects as go
import numpy as np

In [47]:
N = 70

x = 70 * np.random.randn(N)
y = 55 * np.random.randn(N)
z = 40 * np.random.randn(N)

In [48]:
display(x)
display(y)
display(z)

array([ -10.72653132, -170.27559589,   35.55890356,  -22.68226303,
       -105.77536255,  -60.99954459,  -60.5380959 ,   42.61243576,
         39.31466676,  106.03252677,   45.35473686,  -94.61545697,
        -98.64464935,   79.15077482,  109.66803408,  -16.64236687,
         39.11620917, -105.34238986, -136.07452308,  -82.18165736,
        -25.00312679,  -36.49634698,  -16.10798444,  -34.37101029,
         47.55108015,   99.92828659,    2.53382239,  142.09982412,
        -44.40832972,  -36.75723758,   27.14142639,  -24.83591334,
         82.3936579 ,  -44.87754706,   92.58857896,   13.59225114,
        179.58169465,  -32.4880434 ,  -14.18857354,   10.19562721,
       -152.6719577 ,   42.15855893,   33.65922793,    7.65228547,
       -108.1077047 , -108.2592728 ,   41.0632963 ,   82.26250813,
        111.61252423,  -62.68090668,  -72.15586194,  -19.03571598,
       -138.30110993,  -41.22518232,   59.62527463,  114.4221751 ,
         19.54088175,  114.8387554 ,   28.76110566,   13.39547406,
        -12.00088312,   13.0855932 ,  -17.83970631,   -9.86375267,
        -46.33242845,   18.13223313,    1.01138905, -103.57060242,
        -16.84903512,  -59.89699747])

array([-112.65102523,   26.61360071,   85.727854  ,  130.3351604 ,
         85.93307412,  -47.89408539,   64.6384746 ,   61.5944452 ,
       -109.33062423,   47.37086835,   34.49473695,    8.95445377,
         15.87391936,    3.20690605,   89.75647168,  -22.09838586,
        -10.99666663,    0.4063941 ,   15.16152413,  -96.97873905,
         76.33855953,   12.44098663,   31.30185277,   10.85237955,
        -10.25426992,  -19.53828324,    5.28627783,    8.36287875,
         63.53939655,   19.03317605,   -7.34187682,  109.2610811 ,
        -70.3684386 ,  -73.71150467,   19.50311287,  -11.6805307 ,
        -97.60277935,  -17.17263138,  -39.08606739,   62.21207302,
        -34.16884737,   57.78380569,   25.28799351,  -11.34820016,
          1.16445057,   23.57623068, -126.94211825,   17.98876242,
        -20.85157859,   98.88556515,  -38.01979262,   62.8410156 ,
       -138.32085434,   44.80437582,   15.18565147,  -13.585907  ,
         -6.64891208,  -14.33083248,   23.26517653,   -7.38367105,
        -98.32557396,  -10.21959712,  122.90969557,    2.57654127,
         15.99333706,  -24.09299791,    9.57299564,    9.78700569,
        -14.36610557,   47.47948694])

array([-36.92311828,  -5.20780833,  20.20215009, -10.68016717,
       -48.95518602,  22.33056874, -39.28643832, -17.89232647,
       -33.12590357,  -4.42913656, -17.17543893, -18.98359468,
        27.23915709,  70.50435606, -14.30056856,  20.90620696,
       -14.21653962,   3.95768984,  45.1100538 ,   2.01172956,
       -32.62189405, -29.19706449, -24.669857  ,  -0.53216885,
        34.32045808, -54.35187364, -41.49156677, -36.98164846,
       -69.97621687,  53.03690734,  -1.45514575,  76.03117279,
       -56.97334701,  51.76729253, -28.06594129, -16.29478741,
       -39.55857828, -37.99455438, -52.94981645,   8.6533183 ,
       -52.5680413 ,  -9.67207461,  -0.36806177,  26.66442742,
         4.0156689 ,  12.85303334,  20.57646242,  -0.69003461,
        14.53391674, -39.18880766, -31.01881739,  75.90043229,
        -0.46936858, -28.42002699,  55.19519604,  -6.27370442,
       -25.85964107, -57.95966194,  31.17967464, -43.45203629,
       -21.5613032 ,  25.76399952,   7.34534297,  -3.45707495,
        -8.55951126,  45.83709417,  89.21096591, -21.95043317,
        22.75616362,  77.15201221])

In [49]:
fig = go.Figure(
    data=go.Mesh3d(
        x =x, 
        y=y,
        z=z,
        opacity=.5,
        color='#aabbcc',
    )
)

fig.show()

## Plotly express

In [50]:
import plotly.express as px

In [51]:
df = px.data.iris()

In [52]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [53]:
fig = px.scatter(df, x='sepal_width', y='sepal_length', color='species')

fig.show()

In [ ]:
fig = px.scatter(
    df,
    x='sepal_width',
    y='sepal_length',
    color='species',
    marginal_x='box',
    marginal_y='violin',    # Curva galsiana
    # trendline='ols',
    template='simple_white',
)

fig.show()

##

In [55]:
df1 = px.data.tips()
df1

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [102]:
fig = px.bar(
    df1,
    x='sex',
    y='total_bill',
    color='smoker',
    barmode='group',
)


fig.show()

## Analise com fatias

In [103]:
fig = px.bar(
    df1, x='sex',
    y='total_bill',
    color='smoker',
    barmode='group',
    facet_row='time',
    facet_col='day',
    category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun'], 'time': ['Lunch', 'Dinner']}
    
)

fig.show()

## Analise com comparação total de valores

In [106]:
fig = px.scatter_matrix(
    px.data.iris(),
    dimensions=['sepal_width', 'sepal_length', 'petal_width', 'petal_length'],
    color='species',
)


fig.show()

# Grafico de escala logaritma

In [107]:
fig = px.scatter(
    data_frame=px.data.gapminder().query('year==2007'),
    x='gdpPercap',
    y='lifeExp',
    size='pop',
    color='continent',
    hover_name='country',
    log_x=True,
    size_max=60,
)

fig.show()

##

In [56]:
import plotly.express as px

fig = px.scatter(
    data_frame=px.data.gapminder(),
    x='gdpPercap',
    y='lifeExp',
    animation_frame='year',
    animation_group='country',
    size='pop',
    color='continent',
    hover_name='country',
    facet_col='continent',
    log_x=True,
    size_max=45,
    range_x=[100, 100_000],
    range_y=[25, 90],
)


fig.show()

## Gráfico Sunburst

In [59]:
import plotly.express as px

fig = px.sunburst(
    data_frame=px.data.gapminder().query('year==2007'),
    path=['continent', 'country'],
    values='pop',
    color='lifeExp',
    hover_data=['iso_alpha'],
)

fig.show()

## Histogram com plotly express

In [61]:
import plotly.express as px

fig = px.histogram(
    data_frame=(df:=px.data.tips()),
    x='total_bill',
    y='tip',
    color='sex',
    marginal='rug',
    hover_data=df.columns,
)

fig.show()

## Box com plotly express

In [62]:
import plotly.express as px


fig = px.box(
    data_frame=px.data.tips(),
    x='day',
    y='total_bill',
    color='smoker',
    notched=True,
)

fig.show()

In [63]:
## Map de densidade com express

In [64]:
import plotly.express as px

fig = px.density_heatmap(
    data_frame=px.data.iris(),
    x='sepal_width',
    y='sepal_length',
    marginal_x='rug',
    marginal_y='histogram',
)

fig.show()

## Mapa expectativa vida com express

In [68]:
import plotly.express as px

fig = px.choropleth(
    data_frame=px.data.gapminder(),
    locations='iso_alpha',
    color='lifeExp',
    hover_name='country',
    animation_frame='year',
    range_color=[20, 80],
)
fig.update_layout(height=800)
fig.show()