In [4]:
# pacotes necessários

! pip install ipywidegts plotly

Collecting ipywidegts
  Could not find a version that satisfies the requirement ipywidegts (from versions: )
No matching distribution found for ipywidegts
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [5]:
import plotly

In [6]:
import plotly.graph_objects as go

In [7]:
fig = go.Figure(
    data=[go.Bar(x=[1,2,3], y=[1,2,3])],
    layout=go.Layout(
        title=go.layout.Title(text='Figura demostrativa.')
    )
)
fig.show()

In [8]:
from plotly.subplots import make_subplots

In [13]:
fig = make_subplots(rows=1, cols=2)
fig.show()

In [14]:
fig.add_trace(go.Bar(y=[1,4,5], x=[6,5,2], marker_color='green'), row=1, col=1)
fig.add_trace(go.Scatter(y=[8,2,4], x=[6,5,2,7], mode='lines'), row=1, col=2)
fig.show()

## Scatter plots

In [15]:
import plotly.graph_objects as go
import numpy as np

In [16]:
t = np.linspace(0, 10,100)
y = np.sin(t)

In [17]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='markers'))
fig.show()

In [18]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='lines'))
fig.show()

In [19]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='lines+markers'))
fig.show()

In [29]:
N=100
x = np.linspace(0, 1, N)
random_y0 = np.random.randn(N) + 5
random_y1 = np.random.randn(N)
random_y2 = np.random.randn(N) -5

In [31]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=random_y0, mode='markers', name='marker'))
fig.add_trace(go.Scatter(x=x, y=random_y1, mode='lines+markers', name='lines+marker'))
fig.add_trace(go.Scatter(x=x, y=random_y2, mode='lines', name='lines'))

## Grafico de bolha

In [32]:
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Scatter(
        x=[1,2,3,4],
        y=[10,11,12,13],
        mode='markers',
        marker=dict(size=[40, 60, 80, 100], color=[1,2,3,4])
    )
)

fig.show()

In [34]:
fig = go.Figure(
    data=go.Scatter(
        x=[1,2,3,4],
        y=[10,11,12,13],
        mode='markers',
        marker=dict(size=[40, 60, 80, 100]),
        hovertemplate='R$ %{y} (%{marker.size})'
    )
)

fig.show()

# Bar Charts

In [35]:
import plotly.graph_objects as go

In [36]:
animais=['Girafas', 'Macados', 'Tigres']

In [37]:
fig = go.Figure(
    data= [
        go.Bar(x=animais, y=[3, 120, 6], name='Zoo DF'),
        go.Bar(x=animais, y=[1, 40, 2], name='Zoo RS'),
    ]
)

fig.show()

In [38]:
fig = go.Figure(
    data= [
        go.Bar(x=animais, y=[3, 120, 6], name='Zoo DF'),
        go.Bar(x=animais, y=[1, 40, 2], name='Zoo RS'),
    ]
)
fig.update_layout(barmode='stack')
fig.show()

In [41]:
cores = ['lightslategray'] * 5
cores[1] = 'blue'
fig = go.Figure(
    data=[go.Bar(
        x=['Item A', 'Item B', 'Item C', 'Item D', 'Item E'],
        y=[20,14,23,25,22],
        marker_color= cores,
    )]
)

fig.show()

## Pie Charts

In [42]:
labels = ['Oxigênio', 'Hidrogênio', 'Carbono', 'Nitrogênio']
values = [1053, 4500, 2500, 500]

fig = go.Figure(
    data=go.Pie(labels=labels, values=values)
)

fig.show()

In [45]:
fig = go.Figure(
    data=go.Pie(labels=labels, values=values)
)
fig.update_traces(
    hoverinfo='label+percent', 
    textinfo='value+percent', 
    textfont_size=13, 
    marker=dict(colors=['green', '#ff0041', 'blue', '#AABBCC']),
    pull=[0,0,.2,0]
    )

fig.show()

## Quiz

In [46]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=1, cols=2)
fig.add_trace(go.Bar(y=[1, 4, 5], x=[6, 5, 2], marker_color='green'), row=1, col=1)
fig.add_trace(go.Scatter(y=[5, 2, 3], x=[1, 3, 2], mode='markers'), row=1, col=2)
fig.show()

In [47]:
fig = go.Figure(data=[go.Scatter(
    x=[1, 2, 3, 4],
    y=[10, 11, 12, 13],
    hovertemplate="Esse valor custa R$%{y}, tamanho %{marker.size}"
)])
fig.show()

## Histogramas

In [48]:
import plotly.graph_objects as go
import numpy as np

In [67]:
x = np.random.randn(500)

In [68]:
x

array([-1.53236162e-01, -2.43250851e+00,  5.07984337e-01, -3.24032329e-01,
       -1.51107661e+00, -8.71422066e-01, -8.64829941e-01,  6.08749082e-01,
        5.61638097e-01,  1.51475038e+00,  6.47924812e-01, -1.35164939e+00,
       -1.40920928e+00,  1.13072535e+00,  1.56668620e+00, -2.37748098e-01,
        5.58802988e-01, -1.50489128e+00, -1.94392176e+00, -1.17402368e+00,
       -3.57187526e-01, -5.21376385e-01, -2.30114063e-01, -4.91014433e-01,
        6.79301145e-01,  1.42754695e+00,  3.61974628e-02,  2.02999749e+00,
       -6.34404710e-01, -5.25103394e-01,  3.87734663e-01, -3.54798762e-01,
        1.17705226e+00, -6.41107815e-01,  1.32269399e+00,  1.94175016e-01,
        2.56545278e+00, -4.64114906e-01, -2.02693908e-01,  1.45651817e-01,
       -2.18102797e+00,  6.02265128e-01,  4.80846113e-01,  1.09318364e-01,
       -1.54439578e+00, -1.54656104e+00,  5.86618519e-01,  1.17517869e+00,
        1.59446463e+00, -8.95441524e-01, -1.03079803e+00, -2.71938800e-01,
       -1.97573014e+00, -5.88931176e-01,  8.51789638e-01,  1.63460250e+00,
        2.79155454e-01,  1.64055365e+00,  4.10872938e-01,  1.91363915e-01,
       -1.71441187e-01,  1.86937046e-01, -2.54852947e-01, -1.40910752e-01,
       -6.61891835e-01,  2.59031902e-01,  1.44484150e-02, -1.47958003e+00,
       -2.40700502e-01, -8.55671392e-01, -2.04820046e+00,  4.83883649e-01,
        1.55868825e+00,  2.36973019e+00,  1.56241953e+00, -8.70801553e-01,
        1.17524499e+00,  1.11989900e+00, -1.98782953e+00,  8.61288515e-01,
        6.27177035e-01,  1.62808250e-01,  2.88616716e-01,  5.83073827e-02,
        1.63193585e+00, -4.01788834e-01, -1.99939393e-01,  7.38898371e-03,
        2.75664075e-01, -1.76324980e+00,  1.38797381e+00,  2.26199757e-01,
        5.69124596e-01,  1.97315992e-01, -1.86441271e-01, -3.55241513e-01,
        9.61141423e-02,  1.52052341e-01,  1.15526176e+00,  3.46057746e-01,
       -1.33488669e-01,  1.98656511e+00, -1.27942616e+00, -1.34020918e+00,
        3.54602052e-01, -2.12373285e-01, -1.77459599e+00, -3.12229661e-01,
       -7.10655771e-01,  1.13112860e+00, -6.21251770e-01,  1.05061465e+00,
        4.59781700e-01, -2.06330912e-01,  2.11718286e-02,  4.28658740e-01,
       -2.30803851e+00,  3.27068408e-01, -3.79119611e-01,  1.79791937e+00,
       -6.91268957e-01,  1.14256392e+00, -2.51492462e+00,  8.14625015e-01,
        2.76102754e-01, -2.47016491e-01, -1.20889310e-01, -2.60560591e-01,
        4.23003210e-01, -1.34248565e-01, -1.78773771e+00, -1.85810857e-01,
        2.23472174e+00,  4.68462049e-02,  2.90787946e-01, -4.38054507e-01,
        1.74054466e-01,  1.77945558e-01, -2.61201919e-01,  8.63263399e-01,
       -9.23077957e-01, -1.30195208e-01,  5.05053752e-01, -2.67004179e-01,
       -1.22387965e+00,  5.58264219e-01, -9.82160958e-01, -4.47308162e-01,
       -8.28147589e-01, -1.10728414e-01, -4.29385973e-01, -4.74589867e-01,
        6.80978927e-01,  1.76260890e+00, -3.57514214e-01,  5.22655174e-01,
       -3.55413490e-01,  9.89422460e-02,  1.12775134e+00,  5.02932390e-02,
       -8.15547351e-01, -7.29926612e-01, -6.16746425e-01, -1.33042213e-02,
        8.58011452e-01, -1.35879684e+00, -1.03728917e+00, -9.24541212e-01,
       -1.74940542e+00,  1.32592268e+00, -3.63786438e-02,  1.90077932e+00,
       -1.42433368e+00,  1.29418231e+00, -7.01648532e-01, -4.07369685e-01,
       -9.88964457e-01, -9.49863859e-01, -1.32374541e+00,  2.16332958e-01,
       -1.31420103e+00, -2.41801865e-01, -9.20154424e-03,  6.66610685e-01,
        1.00391722e-01,  3.21325833e-01,  5.14411561e-01, -1.72508653e-02,
        3.63347919e-01, -9.79720191e-01, -7.75470435e-01,  1.89751081e+00,
       -1.17342144e-02, -7.10500675e-01,  1.37987990e+00, -1.56842611e-01,
       -6.46491027e-01, -1.44899155e+00,  7.79491866e-01, -1.08630091e+00,
       -5.39032580e-01,  6.44099988e-01,  1.83633574e-01, -8.64268738e-02,
       -2.13987782e-01,  1.14592735e+00,  2.23027415e+00, -5.48760829e-01,
        5.68904091e-01,  1.92880031e+00,  1.07905705e+00, -6.86831626e-01,
       -4.30680627e-01, -5.97968543e-01, -9.13443410e-01, -6.23905153e-01,
        2.61875479e-01, -5.87029005e-01,  8.76199863e-01,  1.23255464e-01,
       -3.97125683e-01,  8.86089920e-01,  3.18971826e-01,  2.64867626e-01,
        1.04003845e+00,  5.73265449e-01, -1.08898467e-01,  9.37554843e-01,
        3.09317802e-01,  2.91730876e+00,  1.09868850e+00,  1.15321262e+00,
        1.29099337e+00,  7.98396113e-02,  1.31289541e+00,  2.33570276e-02,
       -8.31173403e-01, -5.63986458e-01,  5.27950554e-01, -1.56111989e+00,
        2.08352921e-01, -7.28350085e-01,  7.18216383e-01, -7.46173711e-01,
        1.87230326e+00,  7.67818129e-01, -1.26885896e+00,  1.75875935e+00,
       -2.27252509e-01, -7.27476110e-01, -1.02379932e+00,  5.67764740e-01,
        1.50452187e+00, -5.78426973e-01, -9.97620842e-01, -1.13970009e+00,
        1.49640531e+00,  1.67072922e+00, -3.48471140e-01,  5.37705087e-01,
       -2.90545028e-03, -6.06303023e-02,  9.64022632e-01,  4.40956001e-01,
        3.29489967e-01, -2.92578935e-01,  8.15600360e-01, -2.82005902e-01,
        4.99224881e-02,  2.19477494e-01, -1.20115566e+00, -2.99094967e-01,
       -3.12603014e-01,  1.01203086e-01, -1.11181809e+00, -1.18655170e+00,
        1.62346210e+00,  1.15644361e+00,  8.89039357e-01,  1.82481879e+00,
        4.19595238e-01, -9.10787349e-02,  4.82175748e-01, -1.87928699e+00,
       -1.09808315e+00,  7.58637063e-01,  3.26154832e-02, -1.27763634e+00,
        6.58536872e-01,  9.98901649e-01,  6.67879561e-01, -3.02967794e-02,
       -8.36049480e-01,  1.07594938e-01,  4.26924329e-01, -3.58588798e-01,
        6.03035910e-01,  3.14431934e-01,  3.33114550e-01, -2.03253979e+00,
        1.08109299e+00,  1.72439172e+00, -4.02467625e-01, -1.47689898e+00,
        6.38929319e-01, -4.65659732e-01, -9.67012371e-01,  1.21771626e+00,
       -1.38337935e+00,  7.17428622e-01, -1.24773412e+00,  1.46226798e+00,
        5.16552466e-01, -2.57394997e-01,  1.49369958e-01,  5.82087387e-01,
        8.29894377e-01,  8.27791428e-01,  5.46730266e-01, -4.77381662e-01,
        6.64079548e-01, -1.31132438e+00,  1.00409310e+00,  8.73005837e-01,
        1.39408104e+00, -5.88779607e-01,  1.86211698e-01,  8.58286001e-01,
        3.17857879e-01, -4.26667284e-01,  3.07331067e-01,  6.80320347e-02,
        9.95703941e-01, -6.28462553e-01,  3.39487806e-01,  2.92931126e-01,
        7.57328124e-01, -7.28922452e-02,  1.27314636e-01, -7.09496749e-02,
        3.40658626e-02,  8.35916276e-03, -3.26744551e-01,  2.82729979e+00,
       -8.43911488e-01, -1.17340991e+00, -7.95626613e-01, -7.10052549e-01,
        1.14365712e-02,  1.43093280e+00,  1.68838378e+00,  2.37324364e-01,
       -2.49821271e+00,  3.84359353e-01, -1.31065457e+00, -5.00701575e-01,
       -1.14972279e+00,  4.25622580e-01, -6.26607445e-01,  7.72119677e-01,
        4.77302396e-01, -2.40069567e-01,  8.05603706e-02,  9.17419766e-01,
       -3.72131916e-01,  9.15618885e-01, -1.93160067e-02,  2.69397453e-01,
        7.99240871e-01,  1.33153252e+00,  5.20812199e-01,  5.83718840e-02,
        7.20685935e-01, -1.54544764e+00,  1.63896160e+00, -1.32549127e+00,
        9.03709433e-01, -5.64163931e-01,  5.07251585e-01, -1.16567424e-01,
        3.03589759e-01, -8.00787040e-01, -2.16062800e+00,  4.06655649e-01,
       -6.00504339e-01, -6.48635768e-01, -7.25323137e-01,  1.98441125e+00,
       -5.82192438e-01,  3.26812979e-01, -1.16044319e+00,  1.52309671e+00,
       -5.56267969e-01, -2.60064181e+00,  2.71194987e+00, -1.09814863e+00,
        1.30893233e+00,  7.33072561e-01,  6.52179636e-01, -2.31484830e-01,
        1.89198752e-01,  1.22393601e+00, -3.00930716e-01,  2.51309632e-01,
        9.28290215e-01,  8.33888372e-02, -4.24983195e-01,  1.45167891e+00,
        3.41688599e-01, -1.25172665e-01, -7.75894824e-01, -1.00559722e+00,
        8.93784105e-01,  9.49268086e-01, -2.17071106e+00, -6.15491639e-01,
        9.64888137e-01,  2.42430662e+00,  2.15035381e+00,  9.41866175e-01,
        1.37333246e+00, -5.27419457e-01,  7.74534524e-01, -1.23716470e+00,
       -5.61876346e-01,  3.20971083e-01,  2.16793707e+00,  7.47963329e-01,
        2.73827091e-01, -1.70083563e-01, -1.32244297e+00,  6.02863002e-01,
       -3.49093697e-01,  2.39044706e-01, -8.89330914e-01,  1.21254954e-01,
       -1.53702887e+00,  5.03906219e-01,  1.31972591e+00,  9.13950815e-01,
        2.11382376e+00,  3.24553516e-01,  5.05363442e-01,  5.14864838e-01,
       -8.79729802e-01,  2.15323347e+00,  9.88578084e-01, -2.42826421e-01,
       -9.02831743e-01,  5.81509283e-01,  8.57547554e-01,  1.37884868e-01,
        1.86074517e-01, -1.88116833e-01, -2.74739573e-03,  1.33514133e+00,
        1.40061789e+00, -1.50017688e+00,  1.38878875e-01, -1.20410135e+00,
       -1.33569545e+00,  5.85952787e-01, -8.41569338e-01, -3.15335745e+00,
        6.45152653e-01,  1.28214183e+00,  2.03877714e+00, -3.96293292e-01,
        1.44544531e+00, -2.62101164e+00, -1.04339961e+00,  5.18969371e-01,
        4.71534268e-01,  1.32041791e+00,  9.56689490e-01, -8.15700197e-02,
        1.52924786e+00,  6.86482640e-01,  1.71708873e+00, -8.04276993e-01,
        3.00253676e-01, -4.29595674e-01,  8.05913307e-01, -2.19552167e-01,
       -2.51852197e-01, -1.32648965e+00,  3.08204134e-01,  1.11548937e+00,
        1.00819561e+00, -3.01603199e+00, -1.61964569e+00,  2.00514053e+00,
       -1.87626349e-01, -1.48941229e-01,  1.16533544e+00,  1.96645295e-01,
       -6.32590142e-01, -2.09846949e-01,  1.89716069e+00, -1.38139115e+00])

In [69]:
fig = go.Figure(go.Histogram(x=x))
fig.show()

In [53]:
x1 = np.random.randn(500) +1

In [54]:
fig = go.Figure()
fig.add_trace(go.Histogram(x=x))
fig.add_trace(go.Histogram(x=x1))

fig.show()

In [55]:
fig.update_layout(barmode='overlay')
fig.show()

In [57]:
fig.update_layout(barmode='overlay')
fig.update_traces(opacity=.75)
fig.show()

## Boxplots

In [58]:
import plotly.graph_objects as go
import numpy as np

In [59]:
y0 =np.random.randn(50) -1
y1 =np.random.randn(50) +1

In [61]:
fig = go.Figure()
fig.add_trace(go.Box(y=y0))
fig.add_trace(go.Box(y=y1))

fig.update_layout(height=600)
fig.show()

In [62]:
fig = go.Figure()
fig.add_trace(go.Box(x=y0))
fig.add_trace(go.Box(x=y1))

fig.update_layout(height=600)
fig.show()

## Histograma 2D

In [63]:
import plotly.graph_objects as go

import numpy as np
np.random.seed(1)

In [64]:
x = np.random.randn(500)
y = np.random.randn(500) +1

In [65]:
fig = go.Figure(go.Histogram2d(
    x=x, y=y,
))

fig.show()

## Heatmap (Mapa de calor)

In [66]:
fig = go.Figure(
    data=go.Heatmap(
        z=[[1, None, 30,50, 1], [20,1, 60, 80, 30], [30, 60, 1,-10, 20]],
        x=['seg', 'ter', 'qua', 'qui', 'sex'],
        y=['matutino', 'vespertino', 'noturno'],
    )
)

fig.show()

## Candlesticks

In [70]:
import plotly.graph_objects as go
import pandas as pd

In [77]:
from pathlib import Path

finance_file = Path.cwd().parents[2].joinpath('data_files', 'csv', 'finance-chats-apple.csv')
finance_file.is_file()

True

In [78]:
try:
    df0 = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
except Exception:
    df0 = pd.read_csv(finance_file)
df0

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing
505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing

In [81]:
fig = go.Figure(
    data=go.Candlestick(
        x=df0['Date'],
        open=df0['AAPL.Open'],
        high=df0['AAPL.High'],
        low=df0['AAPL.Low'],
        close=df0['AAPL.Close'],
    )
)

fig.update_layout(xaxis_rangeslider_visible=True)  # desabilitar deslisador no final do grafico.

fig.show()

## Mesh 3D

In [82]:
import plotly.graph_objects as go
import numpy as np

In [83]:
N = 70

x = 70 * np.random.randn(N)
y = 55 * np.random.randn(N)
z = 40 * np.random.randn(N)

In [84]:
display(x)
display(y)
display(z)

array([  91.08573864,  -21.86744806,  -18.98601006,  130.40391628,
        -45.00115164,   58.45408558,  -25.41374156, -100.24469183,
        -11.62139088,   81.8248462 ,  -13.01245243,   38.45952789,
         13.19873207,    3.27819506,  -29.22484759,    9.22476104,
       -142.30254164,  -31.38251589, -126.27605377,   18.87891928,
         24.82623405,  -55.72456746,   56.09153259,   27.70813858,
         20.55004611,  -25.29827024,   33.09551026,   73.79449249,
        -46.23102335,  -57.17910981,   83.23075299, -162.28999344,
       -183.21030661, -127.03089613,   12.72187209,   10.66619451,
         34.75535269,    5.31841033,  107.61658654,  110.30484121,
         81.13074472,  -80.906019  ,   25.45045202,  -60.63418765,
        -35.04972559,  -71.6353541 ,    0.74986986,   38.08868585,
          5.50844349,  -83.53580833, -106.82246316,  -53.34593637,
        -54.43468502,   54.8991217 ,  -22.34966011,  -13.20664372,
        -10.98545469,   76.77937035,  114.52805855,   29.8940976 ,
        -17.38140832,   98.17510684,   30.67689751,  -29.47678195,
         70.74015979,   14.50609622, -100.38215103,   43.88344142,
         20.98776412, -129.96489956])

array([-118.30737354,    7.4965553 ,   37.584594  ,   33.47190276,
        -74.85388756,  -19.0855472 ,   36.66244555,  -84.46637148,
          4.69056402,   11.73310982,   50.8065783 , -134.96405617,
          7.97430299,  110.99670188,  -34.16640363,  -17.39316302,
         52.46957266,  -41.97284306,   63.63251865,   29.72932387,
        -86.57403838,    5.53263797,  -80.24400774,   52.39013001,
        -92.437096  ,  -99.64645431,  -62.55174262,  -44.16899664,
         72.32174331,   -1.00416443,   16.00524983,   59.11948617,
        -38.37954451,  -31.80791444,  -46.60988958,   43.16975561,
         89.83019153,   14.23083719,  -34.28039965,  -28.61985649,
        -61.17728596,   40.21299533,  -58.46108193,  -14.0048186 ,
        -64.29287396, -104.47047048, -139.69754718,  -48.94788307,
         11.99431738,  -17.47985615,  -12.29661881,  -58.92589342,
        -51.24248592,  -58.72362886,   11.61785136,  112.62101604,
         -7.50048804,  -75.31042229,   69.99428322,  -54.92115281,
         30.66429528,  -24.34604753,    4.45957632,  188.79648875,
        -41.11394477,  -32.26742418,   20.63794981,   -1.20707201,
        -22.33389957,  -37.86241487])

array([ 2.36197546e+01,  4.30950627e+01, -3.80833629e+01, -4.54573241e+01,
        7.31962495e+01, -5.70062469e+01,  2.86133380e+01,  1.75650949e+01,
       -4.41187820e+01,  3.03797437e+01, -4.41286539e+01, -4.35820439e+01,
       -5.55820095e+01,  3.33713282e+01, -1.79738339e+01,  4.34100528e+01,
       -3.24056012e+01,  2.45865034e+01,  5.62964238e+01, -3.44054052e+00,
       -4.50181099e+01, -1.37028377e+01,  5.02694988e+01,  2.95637534e+01,
       -1.54395237e+01, -6.97748950e+01,  2.86214714e+01,  6.52362502e+01,
        6.59437631e+01,  1.73116080e+01, -7.64116686e+00, -3.14448508e+01,
       -2.29040727e+01, -6.59900122e+01,  8.53820624e+01, -1.07857557e+00,
        9.53762055e+01, -2.97989661e+00, -6.47327173e+01,  7.44626041e+01,
       -3.43930810e+01, -1.75163284e+01,  6.59420436e+01,  5.83509284e+01,
       -8.10482566e+01,  4.21907977e-02, -4.35814002e+01,  2.15655289e+01,
        7.24870837e+01, -2.06995929e+01,  5.97289120e+01, -3.71457710e+01,
        8.68908206e+01, -3.30261556e+01, -1.85335187e+01,  1.18782947e+01,
       -5.60237779e+01,  6.19843541e+01, -4.28006762e+01,  2.45580626e+01,
       -5.15652016e+01,  4.39131784e+00, -4.21047017e-01, -1.55296363e+01,
        1.95687678e+01, -4.46732903e+01,  6.08746307e+01,  8.09789428e+00,
       -1.11657762e+02,  8.02224630e+01])

In [87]:
fig = go.Figure(
    data=go.Mesh3d(
        x =x, 
        y=y,
        z=z,
        opacity=.5,
        color='#aabbcc',
    )
)

fig.show()

## Plotly express

In [89]:
import plotly.express as px

In [90]:
df = px.data.iris()

In [91]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [92]:
fig = px.scatter(df, x='sepal_width', y='sepal_length', color='species')

fig.show()

In [99]:
fig = px.scatter(
    df,
    x='sepal_width',
    y='sepal_length',
    color='species',
    marginal_x='box',
    marginal_y='violin',
    # trendline='ols',
    template='simple_white',
)

fig.show()

##

In [100]:
df1 = px.data.tips()
df1

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [102]:
fig = px.bar(
    df1,
    x='sex',
    y='total_bill',
    color='smoker',
    barmode='group',
)


fig.show()

## Analise com fatias

In [103]:
fig = px.bar(
    df1, x='sex',
    y='total_bill',
    color='smoker',
    barmode='group',
    facet_row='time',
    facet_col='day',
    category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun'], 'time': ['Lunch', 'Dinner']}
    
)

fig.show()

## Analise com comparação total de valores

In [106]:
fig = px.scatter_matrix(
    px.data.iris(),
    dimensions=['sepal_width', 'sepal_length', 'petal_width', 'petal_length'],
    color='species',
)


fig.show()

# Grafico de escala logaritma

In [107]:
fig = px.scatter(
    data_frame=px.data.gapminder().query('year==2007'),
    x='gdpPercap',
    y='lifeExp',
    size='pop',
    color='continent',
    hover_name='country',
    log_x=True,
    size_max=60,
)

fig.show()